### ISSUE TITLE
Poker day to day TODO

### ISSUE THREAD

**Issue by DolevArtzi** [DolevArtzi/probably-probability#13]
- [ ] revisit and fix stat mode
- [ ] start thinking about the interactive mode --> will eventually have agents betting
    - [ ] this includes printing the cards as they're opened, not just at the end
- [ ] probability of falling into each score class
    - [ ] at the end of the round
    - [ ] at each point as the round progresses
- [ ]  enumerate possibilities including all opponent hands
- [ ] probability for each 'node' (won't be a tree yet)
